### ISSUE TITLE
Version 4.7.1 compiled fail on windows 

### ISSUE THREAD

**Issue by jiazhanfeng1989** [zeromq/cppzmq#476]
We used zeromq 4.3.2 and cppzmq 4.6.0 on windows and they work fine,
But after upgrading to zeromq v4.3.4, the compilation failed.

win64-vs14-dbg\include\zeromq/zmq.hpp(2588): error C3646: 'fd': unknown override specifier

# Issue description
we used zeromq  4.3.2 and cppzmq 4.6.0 on windows and they workd fine,
But after upgrading to zeromq  v4.3.4, the compilation failed.

win64-vs14-dbg\include\zeromq/zmq.hpp(2588): error C3646: 'fd': unknown override specifier

# Environment
* OS: windows VS2015

old:  woks fine
zeromq  4.3.2
cppzmq 4.6.0

new:  compile fail
cppzmq v4.7.1
zeromq  4.3.4

# What's the expected result?
Compile OK.

**Comment by gummif** [comment]
Try including winsock2.h before zmq.hpp. This should get fixed when https://github.com/zeromq/cppzmq/pull/452 is merged.

**Comment by jiazhanfeng1989** [comment]
My project does not need to add additional Winsock2.h before upgrading. It seems that zeromq v4.3.4 has changed its internal header dependency. I also failed to compile using cppzmq v4.6.0 & zeromq v4.3.4.

But cppzmq v4.6.0 & zeromq  4.3.2 compiled ok.

**Comment by gummif** [comment]
This was a change in libzmq (https://github.com/zeromq/libzmq/commit/cb211e4f1e031e44dbfdf68f133d1b638f6ca530) that no longer includes winsock2.h, and cppzmq was and is still using SOCKET (in DRAFT mode only).
