### PR TITLE
Fix error: default initialization of an object of const type

### PR DESCRIPTION
**Pull request by jcfr**
This commit fixes a regression introduced in a3e5b54c3 (Problem: Socket
options lack type-safety (#393)).

It addresses the following error reported when building the project
on macOS 10.11.6.

Errors like the following:

```
  cppzmq/zmq.hpp:1325:39: error: default initialization of an object of const type 'const affinity_t' (aka 'const integral_option<4, unsigned long long, false>') without a user-provided default constructor
```

Compiler version:

```
  Apple LLVM version 8.0.0 (clang-800.0.42.1)
  Target: x86_64-apple-darwin15.6.0
  Thread model: posix
  InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Similar issues:

 * https://github.com/tensorflow/tensorflow/issues/28839
  error: default initialization of an object of const type 'const Subgraph::Identity' without a user-provided default constructor

 * https://bugzilla.mozilla.org/show_bug.cgi?id=1451088
   Clang 3.8: error: default initialization of an object of const type 'const js::jit::ArithPolicy' without a user-provided default constructor

 * https://github.com/googleapis/google-cloud-cpp/issues/1593
   [osx] error: default initialization of an object of const type

### CODE REVIEW

File: zmq.hpp [hunk 1]
```diff
@@ -1284,6 +1284,7 @@ namespace sockopt
 // BoolUnit: if true accepts values of type bool (but passed as T into libzmq)
 template<int Opt, class T, bool BoolUnit = false> struct integral_option
 {
+    ZMQ_CONSTEXPR_VAR integral_option(){}
```
Comment (gummif) [inline zmq.hpp:1287]: This can be `constexpr integral_option() noexcept = default;`, same applies to array_option.

Comment (jcfr) [reply zmq.hpp:1287]: Thanks for the review and suggestion. I will try and report back.

Comment (jcfr) [reply zmq.hpp:1287]: It turns out that your suggestion also leads to the following build error on macOS 10.11.6:

```
/path/to/cppzmq/zmq.hpp:1329:39: error: default initialization of an object of const type 'const affinity_t' (aka 'const integral_option<4, unsigned long long, false>') without a user-provided default constructor
ZMQ_DEFINE_INTEGRAL_OPT(ZMQ_AFFINITY, affinity, uint64_t);
                                      ^
```

Comment (jcfr) [reply zmq.hpp:1287]: Let me know if you need me to test anything else to move forward with the integration :pray:

Comment (gummif) [reply zmq.hpp:1287]: OK, I looked into this and I think the best solution is to change the definition macros to `ZMQ_INLINE_VAR ZMQ_CONSTEXPR_VAR NAME##_t NAME{}` (added {}).

Comment (jcfr) [reply zmq.hpp:1287]: Thanks, I will update the PR later this afternoon

Comment (jcfr) [reply zmq.hpp:1287]: This last suggestion also lead to the same error on macOS 10.11.6.

Here is the patch I applied:

```diff
@@ -1299,10 +1301,10 @@ template<int Opt, int NullTerm = 1> struct array_option
     ZMQ_INLINE_VAR ZMQ_CONSTEXPR_VAR NAME##_t NAME
 #define ZMQ_DEFINE_INTEGRAL_BOOL_UNIT_OPT(OPT, NAME, TYPE)                          \
     using NAME##_t = integral_option<OPT, TYPE, true>;                              \
-    ZMQ_INLINE_VAR ZMQ_CONSTEXPR_VAR NAME##_t NAME
+    ZMQ_INLINE_VAR ZMQ_CONSTEXPR_VAR NAME##_t NAME{}
 #define ZMQ_DEFINE_ARRAY_OPT(OPT, NAME)                                             \
     using NAME##_t = array_option<OPT>;                                             \
-    ZMQ_INLINE_VAR ZMQ_CONSTEXPR_VAR NAME##_t NAME
+    ZMQ_INLINE_VAR ZMQ_CONSTEXPR_VAR NAME##_t NAME{}
 #define ZMQ_DEFINE_ARRAY_OPT_BINARY(OPT, NAME)                                      \
     using NAME##_t = array_option<OPT, 0>;                                          \
     ZMQ_INLINE_VAR ZMQ_CONSTEXPR_VAR NAME##_t NAME
```

Comment (gummif) [reply zmq.hpp:1287]: Hmm, did you apply this change to all 5 macros or just those 2?

Comment (jcfr) [reply zmq.hpp]: Updating all for macro addressed the issue. I just forced push the topic.

**Comment by gummif** [comment]
Looks good to me, will have to wait for @sigiesec for approval.

**Comment by jcfr** [comment]
> Looks good to me, will have to wait for @sigiesec for approval.

Sounds good. Thanks again for your help :pray:

**Comment by jcfr** [comment]
Let me know if you need anything else. 

The travis error also seems unrelated:

```
Reading package lists...

Building dependency tree...

Reading state information...

E: Unable to locate package g++-9

E: Couldn't find any package by regex 'g++-9'
apt-get.diagnostics

apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install g++-9 clang-8" failed and exited with 100 during .
```

See https://travis-ci.org/github/zeromq/cppzmq/jobs/683591543

**Comment by sigiesec** [comment]
Thanks for fixing this!

Yes, the travis failure was an infrastructure issue, it went away after retriggering the job.
